import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,AiFillLinkedin,AiFillGithub,AiFillMail} from 'react-icons/ai'
import Image from 'next/image';
import deved from "../public/dev-abhi-wave.png";
import code  from '../public/code.png';
import consulting  from '../public/consulting.png';
import Dataanalysis from '../public/Data analysis.jpg';
import Numpy from '../public/Numpy.jpg';
import Pandas from '../public/Data analysis.jpg';
import Matplotlib from '../public/Data analysis.jpg';
import Seaborn from '../public/Data analysis.jpg';
import MachineLearning from '../public/Machine Learning.jpg';
import ScikitLearn from '../public/Scikit Learn.jpg';
import DeepLearning from '../public/Deep Learning.jpg';
import Pytorch from '../public/Pytorch.jpg';
import TensorFlow from '../public/TensorFlow.jpg';
import NaturalLanguageProcessing from '../public/Natural Language Processing.jpg';
import Spacy from '../public/spacy.jpg';
import NLTK from '../public/NLTK.jpg';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jeshmitha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons dark:text-white">developedbyJesmitha</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() =>setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
            <li>
              <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
          </ul>
        </nav>
        <div className="text-center p-10">
         <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Jesmitha Gunuganthi</h2>
         <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Machine Learning Researcher.</h3>
         <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
          I am a data scientist and generative artist. Previously I went
          to National University of Singapore, EPFL and Duke University.
         </p>
         <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
         Besides data science and data storytelling, I also like
         contemporary art and travelling.
         </p>
         <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
         Having lived in China, Singapore, Switzerland and the United
         States, I understand English, Chinese and French.
         </p>
         <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
         I have given talks and workshops such as Introduction To
         Visualization for Women Who Code and Drawing with Data Workshop
         at Airbnb APAC.
         </p>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
        <AiFillTwitterCircle/>
        <AiFillLinkedin/>
        <AiFillGithub/>
        <AiFillMail/>
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:text-white">
        <Image alt=' ' src={deved} layout="fill"  objectFit="cover"/>
        </div>
        </section>
        <section>
          <div>
             <h3 className="text-3xl py-1 dark:text-white">Skills :</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 dark:text-white">
            <div className="flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' className="rounded-md" src={Dataanalysis} width={150} height={150} />
              <h3 className=" text-gray-800 text-lg font-medium pt-8 pb-2"> Data Analysis Using </h3>
              <p className=" text-gray-800 py-1 flex gap-2 items-center" >Numpy <Image alt=' ' src={"/Numpy.jpg"} width={30} height={30} /></p>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">Pandas <Image alt=' ' src={"/Pandas.jpg"} width={80} height={80} /></p>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">Matplotlib<Image alt=' ' src={"/Matplotlib.jpg"} width={80} height={80} /></p>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">Seaborn<Image alt=' ' src={"/seaborn.jpg"} width={50} height={50} /></p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' 'className="rounded-md" src={MachineLearning} width={150} height={150} />
              <h3 className=" text-gray-800 text-lg font-medium pt-8 pb-2"> Machine Learning </h3>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">Scikit Learn<Image alt=' ' src={"/Scikit Learn.jpg"} width={120} height={120} /></p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' className="rounded-md" src={DeepLearning} width={150} height={150} />
              <h3 className=" text-gray-800 text-lg font-medium pt-8 pb-2 "> Deep Learning Using </h3>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">PyTorch<Image alt=' ' src={"/Pytorch.jpg"} width={80} height={80} /></p>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">TensorFlow<Image alt=' ' src={"/TensorFLow.jpg"} width={80} height={80} /></p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' src={NaturalLanguageProcessing} width={100} height={100} />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 "> NLP(Natural language Processing) Using</h3>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">NLTK<Image className="rounded-md" alt=' ' src={"/NLTK.jpg"} width={70} height={70} /></p>
              <p className=" text-gray-800 py-1 flex gap-2 items-center">SpaCy<Image alt=' ' src={"/Spacy.jpg"} width={70} height={70} /></p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' src={code} width={100} height={100} />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 "> Programming & Data Structures</h3>
              <p className=" text-gray-800 py-1">Python</p>
              <p className=" text-gray-800 py-1">Java</p>
              <p className=" text-gray-800 py-1">C++</p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' src={code} width={100} height={100} />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 "> Web Development Using</h3>
              <p className=" text-gray-800 py-1">HTML</p>
              <p className=" text-gray-800 py-1">CSS</p>
              <p className=" text-gray-800 py-1">Flask</p>
              <p className=" text-gray-800 py-1">SQL</p>
              <p className=" text-gray-800 py-1">mongoDB</p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' src={code} width={100} height={100} />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 "> AWS</h3>
              <p className=" text-gray-800 py-1">Numpy</p>
            </div>
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=' ' src={code} width={100} height={100} />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 "> Other tools</h3>
              <p className=" text-gray-800 py-1">git</p>
              <p className=" text-gray-800 py-1">LINUX</p>
              <p className=" text-gray-800 py-1">docker</p>
              <p className=" text-gray-800 py-1">Terraform</p>
              <p className=" text-gray-800 py-1">jupyter</p>
              <p className=" text-gray-800 py-1">Visual Studio Code</p>
              <p className=" text-gray-800 py-1">Pycharm</p>
            </div>
          </div>
        </section>
        <section> 
        <div> 
         <h3 className="text-3xl py-1 dark:text-white">Career :</h3>
         <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> 
            </p>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          </div>
        </section>
      </main>
    </div>
  );
}
